---
- name: ensure java openjdk
  package:
    name: '{{ nexus_java_package_name }}'
    state: '{{ nexus_java_package_state }}'

- name: extract nexus archive
  unarchive:
    src: '{{ nexus_tmp_archive_file }}'
    dest: '{{ nexus_base_path }}'
    creates: '{{ nexus_base_path }}/.installed'
    remote_src: yes
  when: not ansible_check_mode

- name: ensure owner of installed files
  file:
    path: '{{ nexus_base_path }}'
    owner: '{{ nexus_user_name }}'
    group: '{{ nexus_group_name }}'
    #mode: '0755'
    recurse: yes

- name: ensure empty install file
  copy:
    content: ""
    dest: '{{ nexus_base_path }}/.installed'
    force: no
    owner: '{{ nexus_user_name }}'
    group: '{{ nexus_group_name }}'
    mode: '0644'
