---
- name: import user tasks
  import_tasks: user.yml
  tags:
  - nexus
  - nexus-user

- name: import download tasks
  import_tasks: download.yml
  tags:
  - nexus
  - nexus-download

- name: import directory tasks
  import_tasks: directories.yml
  tags:
  - nexus
  - nexus-dir

- name: import installation tasks
  import_tasks: install.yml
  tags:
  - nexus
  - nexus-install

- name: import configuration tasks
  import_tasks: config.yml
  tags:
  - nexus
  - nexus-config

- name: flush handlers
  meta: flush_handlers

- name: import service tasks
  import_tasks: service.yml
  tags:
  - nexus
  - nexus-service
