---
- name: include user tasks
  import_tasks: user.yml
  tags:
  - nexus
  - nexus-user

- name: include directory tasks
  import_tasks: directories.yml
  tags:
  - nexus
  - nexus-dir

- name: include installation tasks
  import_tasks: install.yml
  tags:
  - nexus
  - nexus-install
